### PR TITLE
Add ports

### PR DESCRIPTION
**Pull request by ouertani**
expose ports part of the configuration

### CODE REVIEW

**Review by sideeffffect — COMMENTED** [review]
Why not both TCP and UDP? We could name it `jibPortsTcp` and `jibPortsUdp`.
Otherwise looks great! :+1:

**Comment by ouertani** [comment]
> Why not both TCP and UDP? We could name it `jibPortsTcp` and `jibPortsUdp`. Otherwise looks great! 👍

@sideeffffect done 👍

**Review by sideeffffect — APPROVED** [review]
Nice!

**Comment by ouertani** [comment]
@schmitch rebased

**Comment by schmitch** [comment]
t4t

**Pull request merged**
