### PR TITLE
migrate to jib-core

### PR DESCRIPTION
**Pull request by schmitch**

### CODE REVIEW

**Comment by coollog** [comment]
@schmitch Let me know if you have any questions while doing this! Would be glad to answer them :)

**Comment by schmitch** [comment]
well at the moment everything is fine. 
Except that I could've put a null value into `setTargetImageCredentialHelperName` which did do nothing, while I can't set `RegistryImage.named(imageReference).addCredentialRetriever()` to null (it will return a NullPointerException.

**Comment by coollog** [comment]
Yea, in the Jib Core API, only fields marked with `javax.annotation.Nullable` are meant to be able to support `null`. This is mostly to surface a potential unsafe operations as early as possible to avoid unintentionally passing `null` to certain places that may cause a NPE later on.

**Comment by schmitch** [comment]
@coollog how can I get a Docker Containerizer?

**Comment by coollog** [comment]
@schmitch Do you mean a `Containerizer` that builds to a Docker daemon? You would need to call `Containerizer.to(DockerDaemonImage)`:

```java
Containerizer.to(DockerDaemonImage.named('myimage'))
```

You can also set the `docker` executable to use and environment variables using the methods on `DockerDaemonImage`.

**Comment by schmitch** [comment]
well actually sadly jib-core now only supports the docker image format v2.2 which does not like my way of packing up layers `Error processing tar file(duplicates of file paths not supported): )`

**Comment by schmitch** [comment]
ok, looks like layerconfiguration on my side was wrong

**Pull request merged**
