### PR TITLE
Use JavaContainerBuilder

### PR DESCRIPTION
**Pull request by sideeffffect**
depends on https://github.com/schmitch/sbt-jib/pull/77

### CODE REVIEW

**Comment by schmitch** [comment]
please can you rebase the mr?

**Comment by sideeffffect** [comment]
Ready to be merged :tada:

**Comment by sideeffffect** [comment]
ready :tada:

**Comment by ouertani** [comment]
Can we expect a new release by this pr ?

**Comment by sideeffffect** [comment]
@schmitch ping :)

**Comment by sideeffffect** [comment]
@schmitch ping :)

**Comment by sideeffffect** [comment]
Hello @schmitch , is there something I can do to move this PR forward?

**Comment by schmitch** [comment]
t4t

**Pull request merged**
