### PR TITLE
try to fix docker image create time which default will show '48 years…

### PR DESCRIPTION
**Pull request by ysde**
try to fix docker image creation time, which shows "48 years ago"

### CODE REVIEW

**Comment by ysde** [comment]
Hi @schmitch 

I'm a sbt noob.

Can you please check the changes are correct or not ?

By the way, can you teach me how to test the code?

Thank you

**Comment by schmitch** [comment]
Actually the Problem is that, setting the Creation Time will make the build unreproduceable, which means that this change is probably bad.

Currently if you create an image with sbt-jib twice with the same content it should be completly identical, even the time. Which means that any docker registry will think that the image is the same, even that it was build differently.

**Comment by schmitch** [comment]
I mean it would be ok, if that would be configurable and default it to false, however the change as is would not be a great idea.

**Comment by ysde** [comment]
I see, thank you.

**Pull request closed without merging**
